/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Surface & Background
        'surface': '#fff8f7',
        'surface-dim': '#e9d5d8',
        'surface-bright': '#fff8f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff0f1',
        'surface-container': '#fde9ec',
        'surface-container-high': '#f7e3e6',
        'surface-container-highest': '#f1dee0',
        'surface-variant': '#f1dee0',
        'surface-tint': '#a33759',
        'background': '#fff8f7',
        // On-surface
        'on-surface': '#23191b',
        'on-surface-variant': '#554245',
        'on-background': '#23191b',
        // Inverse
        'inverse-surface': '#392d30',
        'inverse-on-surface': '#ffecee',
        // Outline
        'outline': '#887175',
        'outline-variant': '#dbc0c4',
        // Primary
        'primary': '#a33759',
        'on-primary': '#ffffff',
        'primary-container': '#f57799',
        'on-primary-container': '#6e0a32',
        'inverse-primary': '#ffb1c2',
        'primary-fixed': '#ffd9e0',
        'primary-fixed-dim': '#ffb1c2',
        'on-primary-fixed': '#3f0018',
        'on-primary-fixed-variant': '#841e41',
        // Secondary
        'secondary': '#94483f',
        'on-secondary': '#ffffff',
        'secondary-container': '#ff9f93',
        'on-secondary-container': '#79332c',
        'secondary-fixed': '#ffdad5',
        'secondary-fixed-dim': '#ffb4aa',
        'on-secondary-fixed': '#3d0604',
        'on-secondary-fixed-variant': '#76312a',
        // Tertiary
        'tertiary': '#805439',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c99475',
        'on-tertiary-container': '#522d15',
        'tertiary-fixed': '#ffdbc8',
        'tertiary-fixed-dim': '#f3ba99',
        'on-tertiary-fixed': '#311301',
        'on-tertiary-fixed-variant': '#653d24',
        // Error
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        'jakarta': ['Plus Jakarta Sans', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'title-lg': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '26px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      borderRadius: {
        'sm': '8px',
        'DEFAULT': '4px',
        'md': '12px',
        'lg': '20px',
        'xl': '24px',
        '2xl': '32px',
        '3xl': '40px',
        'full': '9999px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'margin-mobile': '20px',
        'gutter-mobile': '16px',
        'unit': '8px',
      },
      boxShadow: {
        'card': '0px 4px 20px rgba(0, 0, 0, 0.04)',
        'nav': '0px 8px 30px rgba(245, 119, 153, 0.15)',
        'primary': '0px 8px 30px rgba(245, 119, 153, 0.25)',
        'sos': '0px 12px 40px rgba(163, 55, 89, 0.35)',
        'glass': '0px 4px 20px rgba(0, 0, 0, 0.08)',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { opacity: '0.4', transform: 'scale(1)' },
          '50%': { opacity: '0.8', transform: 'scale(1.1)' },
        },
        'heartbeat': {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '15%': { transform: 'scale(1.15)', opacity: '0.8' },
          '30%': { transform: 'scale(1)', opacity: '1' },
          '45%': { transform: 'scale(1.1)', opacity: '0.9' },
          '70%': { transform: 'scale(1)', opacity: '1' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-12px)' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'sos-pulse': {
          '0%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(245, 119, 153, 0.7)' },
          '70%': { transform: 'scale(1)', boxShadow: '0 0 0 20px rgba(245, 119, 153, 0)' },
          '100%': { transform: 'scale(0.95)', boxShadow: '0 0 0 0 rgba(245, 119, 153, 0)' },
        },
        'typing-dot': {
          '0%, 80%, 100%': { transform: 'scale(0)' },
          '40%': { transform: 'scale(1)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
      animation: {
        'pulse-glow': 'pulse-glow 3s ease-in-out infinite',
        'heartbeat': 'heartbeat 1.5s ease-in-out infinite',
        'float': 'float 6s ease-in-out infinite',
        'fade-up': 'fade-up 1.2s cubic-bezier(0.22, 1, 0.36, 1) forwards',
        'sos-pulse': 'sos-pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'typing-dot': 'typing-dot 1.4s infinite ease-in-out both',
        'slide-up': 'slide-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fade-in 0.8s ease-out forwards',
      },
      backdropBlur: {
        'xs': '4px',
        'glass': '20px',
      },
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
  ],
}
